[terminal]
shell = "/bin/zsh"

[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "2"
WINIT_WAYLAND_SCALE_FACTOR = "2"

[window]
decorations_theme_variant = "Dark"
dimensions = { columns = 80, lines = 25 }
padding = { x = 0, y = 0 } 
dynamic_padding = false
startup_mode = "Windowed"
opacity = 1

[font]
size = 15.0
normal = { family = "Source Code Pro", style = "Regular" }

[colors]
primary = { background = "#181818", foreground = "#c5c8c6" }
cursor = { text = "#1d1f21", cursor = "#c5c8c6" }

[colors.bright]
black = "#444444"
red = "#FF2740"
green = "#ABE15B"
yellow = "#FFD242"
blue = "#0092FF"
magenta = "#9A5FEB"
cyan = "#67FFF0"
white = "#FFFFFF"

[colors.normal]
black = "#232323"
red = "#FF000F"
green = "#8CE10B"
yellow = "#FFB900"
blue = "#008DF8"
magenta = "#6D43A6"
cyan = "#00D8EB"
white = "#FFFFFF"

[scrolling]
history = 10000

[cursor]
style = "Block"

[mouse]
hide_when_typing = true

