# !/bin/bash
# ~/.xinitrc

setxkbmap -option caps:none
setxkbmap -layout us,ru -option "grp:caps_toggle"

feh --no-fehbg --bg-fill ~/legacy/Wallpapers/mountains_peaks_fog_134301_3840x2400.jpg
redshift -l 55.751244:37.618423 &

diodon &
picom --config $HOME/.config/picom/picom.conf  &

slstatus &
exec dwm
