# ~/.config/zsh/aliases.zsh

alias gad='git add'
alias gaa='git add -A'
alias gcm='git commit'
alias gca='git commit -a'
alias gcma='git commit --amend'
alias gcaa='git commit -a --amend'
alias gph='git push'
alias gpf='git push --force'
alias gplr='git pull -r'
alias gpln='git pull --no-rebase'
alias gre='git rebase'
alias gri='git rebase -i'
alias gbra='git branch -a'
alias gbr='git branch'
alias gsw='git switch'
alias gst='git status -sb'
alias glg='git log --graph --decorate --pretty=oneline --abbrev-commit'
alias gdf='git diff'
alias gdfs='git diff --staged'

alias cmk='cmake -S . -G Ninja -B build --DCMAKE_BUILD_TYPE=Debug'
alias cbld='cmake --build build/ -j$(nproc)'
alias ctst='cbld --target test -j$(nproc)'
alias clfg='find . \( -name "*.cpp" -o -name "*.hpp" -o -name "*.h" \) -not -path "./build/*" -exec clang-format -i {} \;'

alias top='sudo btop'
alias ping='ping -c 2'
alias md='mkdir -p'
alias rd='rmdir'
alias df='df -hT'
alias cls='clear'
alias ll='eza --header --long --group --git -Alh --sort=name'
alias l='eza -1'
alias ls='eza -Ah'
alias tree='eza -T'
#alias cpy='wl-copy'
alias cpy='xclip -selection clipboard'
alias cat='bat --style plain --paging never --theme OneHalfDark'
alias bat='bat --theme OneHalfDark'

alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias dow='cd ~/Downloads'
alias doc='cd ~/Documents'

alias ins='sudo dnf install'
alias upd='sudo dnf update'
alias cxx='eval "$CXX $CXXFLAGS"'
alias ed='${EDITOR}'
alias sour='source ${ZDOTDIR}/.zshrc'
