alias gad='git add'
alias gaa='git add -A'
alias gcm='git commit'
alias gca='git commit -a'
alias gcma='git commit --amend'
alias gcaa='git commit -a --amend'
alias gph='git push'
alias gpo='git push origin'
alias gpf='git push --force'
alias gplr='git pull -r'
alias gpln='git pull --no-rebase'
alias gre='git rebase'
alias gri='git rebase -i'
alias gbra='git branch -a'
alias gbr='git branch'
alias gsw='git switch'
alias gdf='git diff'
alias gst='git status -sb'
alias glg='git log --graph --decorate --pretty=oneline --abbrev-commit'

alias cmk='cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug'
alias cbld='cmake --build build/'
alias rebld='cmk && cbld'
alias ctst='cmake --build build/ && ctest --progress --test-dir build/ --output-on-failure'
alias clfg='find . \( -name "*.cpp" -o -name "*.hpp" -o -name "*.h" \) -not -path "./build/*" -exec clang-format -i {} \;'

alias top='sudo btop'
alias ping='ping -c 2'
alias md='mkdir -p'
alias rd='rmdir'
alias cls='clear'
alias ll='exa --header --long --group --git -Alh --sort=name'
alias l='eza -1'
alias ls='eza -Ah'
alias tree='eza -T'
alias cpy='wl-copy'
alias cat='bat --style plain --paging never --theme OneHalfDark'
alias bat='bat --theme OneHalfDark'
alias ins='sudo dnf install'
alias upd='sudo dnf update'

alias ..='cd ..'
alias ...='cd ../..'
alias dow='cd ~/Downloads'
alias doc='cd ~/Documents'

alias ed='${EDITOR}'
alias edz='${EDITOR} ${ZDOTDIR}/.zshrc'
alias edb='${EDITOR} ~/.bashrc'
alias edvi='${EDITOR} ~/.config/nvim/init.vim'
alias edclangf='${EDITOR} ~/.clang-format'
alias sour='source ${ZDOTDIR}/.zshrc'

